#!/bin/bash
# 測試部署腳本（CPU 版本）

echo "=== Digital Ocean CPU 測試部署 ==="
echo ""
echo "步驟 1：SSH 連到 Web Server"
echo "  ssh root@178.128.54.195"
echo ""
echo "步驟 2：創建測試目錄"
echo "  mkdir -p ~/yolo-test && cd ~/yolo-test"
echo ""
echo "步驟 3：上傳檔案（在本地執行）"
echo "  scp temp/aws_deploy.tar.gz root@178.128.54.195:~/yolo-test/"
echo ""
echo "步驟 4：解壓並安裝"
echo "  cd ~/yolo-test"
echo "  tar -xzf aws_deploy.tar.gz"
echo "  python3 -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo ""
echo "步驟 5：設定環境變數"
echo "  nano .env  # 填入 LiveKit 憑證"
echo ""
echo "步驟 6：測試運行（CPU 模式）"
echo "  python ai_bot.py"
echo ""
echo "注意：CPU 會很慢，但可以驗證程式邏輯！"
